(define-module (chiko services networking)
  #:use-module (guix gexp)
  #:use-module (guix packages)
  #:use-module (gnu services)
  #:use-module (guix records)
  #:use-module (gnu services configuration)
  #:use-module (gnu packages admin)
  #:use-module (gnu system privilege)
  #:use-module (srfi srfi-1)
  #:use-module (srfi srfi-13)
  #:export (chiko-xxx-networking))

(define chiko-xxx-networking)
